server:
  port: 9001
spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/XiaoMoSpringCloud/config
          username: shenghe_game@163.com
          password: shenghe2017
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8001/eureka/,http://eureka2:8002/eureka/,http://eureka3:8003/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
